export const SEND_MESSAGE = "SEND_MESSAGE";
export const DELETE_CHAT = "DELETE_CHAT";
export const RELEASE_BTC = "RELEASE_BTC";
export const READ_MESSAGE = "READ_MESSAGE";
export const SWITCH_USER = "SWITCH_USER";
export const FETCH_CURRENCY = "FETCH_CURRENCY";
export const FETCH_CURRENCY_SUCCESS = "FETCH_CURRENCY_SUCCESS";
export const FETCH_CURRENCY_FAILURE = "FETCH_CURRENCY_FAILURE";